export const elements = {
  apiBaseUrl: document.getElementById('apiBaseUrl'),
  saveApiBaseUrl: document.getElementById('saveApiBaseUrl'),
  statusPanel: document.getElementById('statusPanel'),
  connectionStatus: document.getElementById('connectionStatus'),
  taskCountValue: document.getElementById('taskCountValue'),
  registerForm: document.getElementById('registerForm'),
  loginForm: document.getElementById('loginForm'),
  logoutButton: document.getElementById('logoutButton'),
  currentUserName: document.getElementById('currentUserName'),
  currentUserEmail: document.getElementById('currentUserEmail'),
  roleBadge: document.getElementById('roleBadge'),
  taskForm: document.getElementById('taskForm'),
  taskFormTitle: document.getElementById('taskFormTitle'),
  cancelEditButton: document.getElementById('cancelEditButton'),
  refreshTasksButton: document.getElementById('refreshTasksButton'),
  tasksMeta: document.getElementById('tasksMeta'),
  tasksList: document.getElementById('tasksList'),
  responseLog: document.getElementById('responseLog'),
  taskId: document.getElementById('taskId'),
  title: document.getElementById('title'),
  description: document.getElementById('description'),
  status: document.getElementById('status'),
  searchInput: document.getElementById('searchInput'),
  statusFilter: document.getElementById('statusFilter'),
  sortFilter: document.getElementById('sortFilter'),
  filtersForm: document.getElementById('filtersForm')
};
