export const elements = {
  apiBaseUrl: document.getElementById('apiBaseUrl'),
  saveApiBaseUrl: document.getElementById('saveApiBaseUrl'),
  connectionStatus: document.getElementById('connectionStatus'),
  registerForm: document.getElementById('registerForm'),
  loginForm: document.getElementById('loginForm'),
  logoutButton: document.getElementById('logoutButton'),
  currentUser: document.getElementById('currentUser'),
  taskForm: document.getElementById('taskForm'),
  taskFormTitle: document.getElementById('taskFormTitle'),
  cancelEditButton: document.getElementById('cancelEditButton'),
  refreshTasksButton: document.getElementById('refreshTasksButton'),
  tasksMeta: document.getElementById('tasksMeta'),
  tasksList: document.getElementById('tasksList'),
  responseLog: document.getElementById('responseLog'),
  clearLogButton: document.getElementById('clearLogButton'),
  taskId: document.getElementById('taskId'),
  title: document.getElementById('title'),
  description: document.getElementById('description'),
  status: document.getElementById('status'),
  searchInput: document.getElementById('searchInput'),
  statusFilter: document.getElementById('statusFilter'),
  sortFilter: document.getElementById('sortFilter'),
  filtersForm: document.getElementById('filtersForm')
};
